<?php

class Calculator
{
    public $batteryHealth;

    public function __construct()
    {
        $this->batteryHealth = 0;
    }

    public function __destruct()
    {
        echo PHP_EOL . "---------- End of Program ----------" . PHP_EOL;
    }

    function addition($number1, $number2, $batteryReduction = 10)
    {
        $this->batteryHealth -= $batteryReduction;
        if ($this->batteryHealth <= 0) {
            $this->batteryHealth = 0;
            echo "Your phone need charge" . PHP_EOL;
            return false;
        }
        return $number1 + $number2;
    }

    function subtraction($number1, $number2, $batteryReduction = 10)
    {
        $this->batteryHealth -= $batteryReduction;
        if ($this->batteryHealth <= 0) {
            $this->batteryHealth = 0;
            echo "Your phone need charge" . PHP_EOL;
            return false;
        }
        return $number1 - $number2;
    }

    function multiplication($number1, $number2, $batteryReduction = 10)
    {
        $this->batteryHealth -= $batteryReduction;
        if ($this->batteryHealth <= 0) {
            $this->batteryHealth = 0;
            echo "Your phone need charge" . PHP_EOL;
            return false;
        }
        return $number1 * $number2;
    }

    function division($number1, $number2, $batteryReduction = 10)
    {
        $this->batteryHealth -= $batteryReduction;
        if ($this->batteryHealth <= 0) {
            $this->batteryHealth = 0;
            echo "Your phone need charge" . PHP_EOL;
            return false;
        }
        return $number1 / $number2;
    }

    function exponent($number1, $number2, $batteryReduction = 10)
    {
        $this->batteryHealth -= $batteryReduction;
        if ($this->batteryHealth <= 0) {
            $this->batteryHealth = 0;
            echo "Your phone need charge" . PHP_EOL;
            return false;
        }
        return pow($number1, $number2);
    }

    function charge()
    {
        $this->batteryHealth += 20;
        echo "Now your battery health is $this->batteryHealth%" . PHP_EOL;
    }
}

class FrugalCalculator extends Calculator
{
    function addition($number1, $number2, $batteryReduction = 5)
    {
        return parent::addition($number1, $number2, 5); // TODO: Change the autogenerated stub
    }

    function subtraction($number1, $number2, $batteryReduction = 5)
    {
        return parent::subtraction($number1, $number2, 5); // TODO: Change the autogenerated stub
    }

    function multiplication($number1, $number2, $batteryReduction = 5)
    {
        return parent::multiplication($number1, $number2, 5); // TODO: Change the autogenerated stub
    }

    function division($number1, $number2, $batteryReduction = 5)
    {
        return parent::division($number1, $number2, 5); // TODO: Change the autogenerated stub
    }

    function exponent($number1, $number2, $batteryReduction = 5)
    {
        return parent::exponent($number1, $number2, $batteryReduction); // TODO: Change the autogenerated stub
    }

}

function thriftyCalculatorCalculation()
{
    $calculator = new FrugalCalculator();
    calculationCalculator($calculator);
}

function generalCalculatorCalculation()
{
    $calculator = new Calculator();
    calculationCalculator($calculator);
}

function calculationCalculator($calculator)
{
    $lastCalculation = null;

    while (1) {
        echo "Kamu ingin operasi matematika yang mana?" . PHP_EOL;
        echo "1. Penambahan" . PHP_EOL;
        echo "2. Pengurangan" . PHP_EOL;
        echo "3. Perkalian" . PHP_EOL;
        echo "4. Pembagian" . PHP_EOL;
        echo "5. Perpangkatan" . PHP_EOL;
        echo "6. Charge" . PHP_EOL;

        $input_operation = fopen("php://stdin", "r");
        $operation = trim(fgets($input_operation));

        if ($operation == '6') {
            $calculator->charge();
            continue;
        }

        if ($lastCalculation == null) {
            echo "Angka 1 : ";
            $input_number_one = fopen("php://stdin", "r");
            $number_one = (int)trim(fgets($input_number_one));
        } else
            $number_one = $lastCalculation;

        echo "Angka 2 : ";
        $input_number_two = fopen("php://stdin", "r");
        $number_two = trim(fgets($input_number_two));

        switch ($operation) {
            case "1":
                $lastCalculation = $calculator->addition($number_one, $number_two);
                if ($lastCalculation == false) {
                    break;
                } else
                    echo "Hasil perhitungan : $lastCalculation" . PHP_EOL;
                break;
            case "2":
                $lastCalculation = $calculator->subtraction($number_one, $number_two);
                if ($lastCalculation == false) {
                    break;
                } else
                    echo "Hasil perhitungan : $lastCalculation" . PHP_EOL;
                break;
            case "3":
                $lastCalculation = $calculator->multiplication($number_one, $number_two);
                if ($lastCalculation == false) {
                    break;
                } else
                    echo "Hasil perhitungan : $lastCalculation" . PHP_EOL;
                break;
            case "4":
                $lastCalculation = $calculator->division($number_one, $number_two);
                if ($lastCalculation == false) {
                    break;
                } else
                    echo "Hasil perhitungan : $lastCalculation" . PHP_EOL;
                break;
            case "5":
                $lastCalculation = $calculator->exponent($number_one, $number_two);
                if ($lastCalculation == false) {
                    break;
                } elseif ($lastCalculation > 1000000) {
                    $lastCalculation = null;
                    echo "Nilai diluar batas yang ditentukan" . PHP_EOL;
                }else
                    echo "Hasil perhitungan : $lastCalculation" . PHP_EOL;
        }
    }
}

echo "------- Choose the calculator -------" . PHP_EOL;
echo "1. Frugal Calculator" . PHP_EOL;
echo "2. General Calculator" . PHP_EOL;
echo "Calculator : ";
$input_calculator_type = fopen("php://stdin", "r");
$calculator_type = trim(fgets($input_calculator_type));

if ($calculator_type == "1") {
    thriftyCalculatorCalculation();
} elseif ($calculator_type == "2") {
    generalCalculatorCalculation();
} else {
    echo "Calculator Type Not Found!";
}
